name: gukgung_siji
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+5
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  video_player: ^2.9.2
  audioplayers: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/videos/sugo.mp4
    - assets/videos/congrats.mp4
    - assets/videos/molki.mp4
    - assets/videos/fire.mp4
    - assets/sounds/arrow_impact.mp3